services:
  backend: &backend
    build: 
      context: ./services/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./services/backend:/app
    env_file:
      - .env
  
  backendcelery:
    <<: *backend
    entrypoint: ./entrypoint/worker.sh
    depends_on:
      - backend
    ports:
      - "8001:8001"

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin@123
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  pgadmin_data:

networks:
  default:
    name: review-app-network